# Generated by Django 4.2.6 on 2024-03-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='descrition',
            new_name='description',
        ),
    ]
